import { DifficultyLevel, DifficultySettings } from '../types';

export const DIFFICULTIES: Record<DifficultyLevel, DifficultySettings> = {
  [DifficultyLevel.VERY_EASY]: {
    name: 'Very Easy',
    nameRu: 'Очень лёгкий',
    hearts: 10,
    damagePerHit: 0.5,
    lavaSpeed: 15,
    lavaColor: 0xff3300,
    targetFloors: 10,
    heartSpawnChance: 0.3,
    patternWeights: { easy: 0.9, medium: 0.1, hard: 0, special: 0.2 },
  },
  [DifficultyLevel.EASY]: {
    name: 'Easy',
    nameRu: 'Лёгкий',
    hearts: 8,
    damagePerHit: 0.5,
    lavaSpeed: 20,
    lavaColor: 0xff3300,
    targetFloors: 25,
    heartSpawnChance: 0.25,
    patternWeights: { easy: 0.7, medium: 0.3, hard: 0, special: 0.15 },
  },
  [DifficultyLevel.NORMAL]: {
    name: 'Normal',
    nameRu: 'Нормальный',
    hearts: 5,
    damagePerHit: 1,
    lavaSpeed: 30,
    lavaColor: 0xff6600,
    targetFloors: 60,
    heartSpawnChance: 0.15,
    patternWeights: { easy: 0.4, medium: 0.5, hard: 0.1, special: 0.1 },
  },
  [DifficultyLevel.HARD]: {
    name: 'Hard',
    nameRu: 'Сложный',
    hearts: 3,
    damagePerHit: 1,
    lavaSpeed: 45,
    lavaColor: 0xff9933,
    targetFloors: 120,
    heartSpawnChance: 0.08,
    patternWeights: { easy: 0.2, medium: 0.5, hard: 0.3, special: 0.05 },
  },
  [DifficultyLevel.HARDCORE]: {
    name: 'Hardcore',
    nameRu: 'Хардкор',
    hearts: 2,
    damagePerHit: 1,
    lavaSpeed: 60,
    lavaColor: 0xffcc00,
    targetFloors: 199,
    heartSpawnChance: 0.03,
    patternWeights: { easy: 0.1, medium: 0.4, hard: 0.5, special: 0.02 },
  },
};
